name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.DOCKER_PUSH_SECRET }}" | docker login ghcr.io -u AFCgooner29 --password-stdin

      - name: Build Docker image
        run: |
          ls
          docker build -f ./Dockerfile -t ghcr.io/afcgooner29/search-dashboard:latest .

      - name: Push Docker image to GitHub Packages
        run: |
          docker push ghcr.io/afcgooner29/search-dashboard:latest

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@13.233.65.84 << EOF
            echo "${{ secrets.DOCKER_PUSH_SECRET }}" | sudo docker login ghcr.io -u AFCgooner29 --password-stdin
            sudo docker pull ghcr.io/afcgooner29/search-dashboard:latest
            sudo docker stop frontend || true
            sudo docker rm frontend || true
            sudo docker run -d --name frontend -p 3000:80 ghcr.io/afcgooner29/search-dashboard:latest
          EOF
