name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

            # ✅ Build Docker image
      - name: Build Docker image
        run: |
          docker login --username AFCgooner29 --password ${{ secrets.DOCKER_PUSH_SECRET }} ghcr.io
          docker build -t ghcr.io/afcgooner29/search-dashboard:latest .
          docker push ghcr.io/afcgooner29/search-dashboard:latest
          
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
      # ✅ Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@13.233.65.84 << EOF
            sudo docker login --username AFCgooner29 --password ${{ secrets.DOCKER_PUSH_SECRET }} ghcr.io
            sudo docker pull ghcr.io/afcgooner29/search-dashboard:latest
            sudo docker stop frontend || true
            sudo docker rm frontend || true
            sudo docker run -d --name frontend -p 8080:8080 ghcr.io/afcgooner29/search-dashboard:latest
          EOF
